Dockerizing
SpaceyaTech/Team-Rio-Django pull request #30
Opened 2022-11-09 18:33 UTC by hellen-22

I am trying to dockerize but i'm getting errors. I have commented out the database part due to the errors. Some guidance needed.

2022-11-09 19:42 UTC, JimmyTron commented
What nature is the error you are having

2022-11-09 19:47 UTC, hellen-22 commented
The database is not connecting
I'm getting this error - django.db.utils.OperationalError: could not translate host name "db" to address: Unknown host

2022-11-09 21:45 UTC, JimmyTron requested changes
Lets first get it right before we can approve it for merging

2022-11-10 08:25 UTC, sangkips commented on CMS/settings.py
> +DATABASES = {
Can you paste your Dockerfile and docker-compose here?

2022-11-10 14:16 UTC, hellen-22 commented on CMS/settings.py
> +DATABASES = {
Dockerfile: 
FROM python:alpine

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY requirements.txt .

RUN pip install -r requirements.txt
COPY . .

Docker compose.
version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

volumes:
  postgres_data:

2022-11-10 19:40 UTC, sangkips commented on CMS/settings.py
> +DATABASES = {
Also I have a different opinion on using alpine images when it comes to building Python images. Linux distributions use the GNU version (glibc) of the standard C library that is required by pretty much every C program, including Python. But Alpine Linux uses musl, those binary wheels are compiled against glibc, and therefore Alpine disabled Linux wheel support.

2022-11-11 06:44 UTC, hellen-22 commented on CMS/settings.py
> +DATABASES = {
I changed to just a python image but still getting errors.. Would you try dockerizing and see if you'll be successful then push we see.

2022-11-11 07:34 UTC, sangkips commented on CMS/settings.py
> +DATABASES = {
Can you be in a pposition to build docker image alone from the docker file? Like running, `docker build . -t sangkips/django-blog:latest`

2022-11-11 07:40 UTC, sangkips commented on CMS/settings.py
> +DATABASES = {
## Try this Dockerfile
``` FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

RUN apt update && apt install -y g++ libpq-dev gcc musl-dev

COPY requirements.txt .

RUN python3 -m pip install -r requirements.txt

COPY . . ```

2022-11-11 07:44 UTC, sangkips commented on CMS/settings.py
> +DATABASES = {
Before you even create a `docker-compose.yml` file just check if that dockerfile can build successfully

2022-11-11 07:53 UTC, sangkips commented on CMS/settings.py
> +DATABASES = {
Where you get the images go to `dockerhub.com` and search the image you want to use

2022-11-14 10:33 UTC, Fredrick-Waihenya commented on CMS/settings.py
> +DATABASES = {
try changing the image and add this command to the ``docker-compose.yml ``:
```web:
    build: .
    command: bash -c "python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"
```

2022-11-15 02:55 UTC, hellen-22 commented on CMS/settings.py
> +DATABASES = {
This worked

2022-11-15 12:40 UTC, nyandika commented
Is there a reason to be dockerizing at this point?
I can understand the use case for it, but for people getting started into the project with not much experience in the area I dont particularly see if the benefits outweigh what could possibly be a steeper learning curve

2022-11-18 21:09 UTC, closed without merging