changing the account model from the blog app to account app
SpaceyaTech/Team-Rio-Django pull request #37
Opened 2022-11-17 10:17 UTC by hellen-22

2022-11-17 11:19 UTC, JimmyTron approved these changes

2022-11-17 11:30 UTC, JimmyTron requested changes
you should also change the registered models on the admin.py 

```
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from .models import *

"""
Registering user model to the admin and extending the UserAdmin so that the user admin page looks like the default user admin panel
List_display specifies the attributes that will appear on the admin page.
add_fieldsets specifies the attributes to be using when creating a user on the admin panel
"""
@admin.register(User)
class CustomUserAdmin(UserAdmin):
    list_display = ('email', 'is_staff', 'is_active',)
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('email', 'username','password1', 'password2', 'is_staff', 'is_active')}
        ),
    )

admin.site.register(Profile)
```

2022-11-17 13:04 UTC, JimmyTron approved these changes
Looks fine

2022-11-18 06:59 UTC, sangkips requested changes

2022-11-18 06:59 UTC, sangkips commented on accounts/models.py
>      email = models.EmailField(unique=True)
Add max_length to the email to avoid users creating long fake emails

2022-11-18 08:49 UTC, sangkips approved these changes
Good

2022-11-18 08:51 UTC, merged