Authentication Implementation
SpaceyaTech/Team-Rio-Django pull request #61
Opened 2022-12-01 07:37 UTC by hellen-22

# Description

Implemented authentication and implemented creation of accounts.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Wrote tests for the various endpoints.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-05 13:56 UTC, JimmyTron reviewed
So far its ok check on highlighted areas if you need to make changes

2022-12-08 20:39 UTC, JimmyTron approved these changes
Satisfies the basics and covers the issue of user creation and  accounts. 
since we will have one instance of the user but various instances of which our users would be able to interact.

2022-12-14 06:56 UTC, OyugoObonyo requested changes
Please consider making the suggested changes. Revert back in case of any issues.

2022-12-14 06:56 UTC, OyugoObonyo commented on .github/workflows/django.yml
> +        pytest
Try using the Django unit-tests already adopted by the project. One of the jobs must go, it doesn't make sense to have 2 jobs running the same exact tests.

2022-12-14 06:56 UTC, OyugoObonyo commented on accounts/serializers.py
> +        fields = ['id', 'account_name', 'bio']
Attempt resolving the display photo 301 error.

2022-12-14 06:56 UTC, OyugoObonyo commented on accounts/views.py
> +class RegisterAccountViewSet(CreateModelMixin, RetrieveModelMixin, ListModelMixin, GenericViewSet):
Preferably, create  Retrieve view set separately from the Register Account View set. A retrieve or list view isn't required at a Register account viewset

2022-12-14 06:56 UTC, OyugoObonyo commented on accounts/views.py
> +    permission_classes = [IsAdminUser]
Admin permissions to register an account isn't really ideal. Reconsider this.

2022-12-14 09:39 UTC, hellen-22 commented on accounts/serializers.py
> +        fields = ['id', 'account_name', 'bio']
> What of profile pic. I suppose the account could have more fields

Profile picture is an optional field. Do i really need to add it to the fields.

2022-12-14 09:40 UTC, hellen-22 commented on accounts/serializers.py
> +        fields = ['id', 'account_name', 'bio']
> Attempt resolving the display photo 301 error.

I figured out what the issue was. I'd just added it to the fields and not in the creation of model step.

2022-12-17 12:57 UTC, merged