80 correct spacing
SpaceyaTech/Team-Rio-Django pull request #81
Opened 2023-01-12 17:42 UTC by IanoNjuguna

# Description

I added a space at the beginning of the directions to setup the env to make it more readable.

Fixes #80 

## Type of change

Please delete options that are not relevant.

- [ x ] New feature (non-breaking change which adds functionality)

2023-01-12 17:54 UTC, jumalaw98 submitted a review, later dismissed
Please work on the conflicts of the pr 
![9E0EAEBB-BBEF-4BC9-806C-6508FF6901FD](https://user-images.githubusercontent.com/41073697/212142465-655bfddf-9dc8-4f7f-a9cf-9f73bc5e586d.png)

2023-01-12 18:02 UTC, JimmyTron requested changes

2023-01-12 18:02 UTC, JimmyTron commented on contributions.md
> +
Refactor these lines

2023-01-13 12:21 UTC, Barissa-Imran approved these changes

2023-01-13 23:41 UTC, JimmyTron approved these changes

2023-01-13 23:44 UTC, JimmyTron approved these changes

2023-01-13 23:49 UTC, merged

2023-01-13 23:49 UTC, Barissa-Imran commented
Great